# ============================
# CultivApp - PostgreSQL Configuration
# ============================

# spring.datasource.url=jdbc:postgresql://localhost:5432/optimu
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.username=postgres
# spring.datasource.password=optimu

# ============================
# JPA / Hibernate Configuration
# ============================

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true

# # ============================
# SQL Script Initialization
# ============================

spring.sql.init.mode=never
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql
# spring.sql.init.continue-on-error=false

# ============================
# H2 (commented out)
# ============================

spring.datasource.url=jdbc:h2:file:./server/.data/optimu-dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.h2.console.enabled=true
# spring.h2.console.enabled=false
