spring.application.name=optimizacionespacios


# ============================
# Perfil activo
# ============================
spring.profiles.active=dev

# ============================
# JPA / Hibernate
# ============================

# Asegura que data.sql se ejecute después de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true

# Mostrar o no las consultas SQL en consola
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Evita problemas con lazy loading en vistas
spring.jpa.open-in-view=false

# ============================
# Servidor
# ============================
server.port=8080

# Incluir mensajes de error en las respuestas de la API
server.error.include-message=always
server.error.include-binding-errors=always

# ============================
# JWT Security
# ============================
security.jwt.secret=optimu-dev-secret-please-change-32-bytes-min
security.jwt.exp-minutes=120 
